version: "3"
services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
volumes:
  dbdata:
  pgadmin_data: